spring:
  # 环境配置
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: base:session
  redis:
    host: localhost
    port: 6379
    database: 0
  thymeleaf:
    cache: false # 关闭缓存
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    suffix: .html
    encoding: UTF-8 # 指定字符集编码

# 服务配置
server:
  port: 80
  servlet:
    context-path: /

# MyBatis配置
mybatis:
  type-aliases-package: com.wia.base.model
  mapper-locations: "classpath:mappers/*.xml"

# Share 服务器
smb:
  name: Share
  password: Share
  ip: 192.168.1.110
  folder: Share