spring:
  # 环境配置
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: base:session
  redis:
    host: localhost
    port: 6379
    database: 0


# 服务配置
server:
  port: 8080
  servlet:
    context-path: /base

# MyBatis配置
mybatis:
  type-aliases-package: com.wia.base.model
  mapper-locations: "classpath:mappers/*.xml"